facepage/urls.py
#from posts.views import getProfilePosts
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from posts.views import profile_view

urlpatterns = [
    path(r'admin/', admin.site.urls, name='admin'),
    path(r'', include('users.urls'), name='users'),
    path(r'home/', include('posts.urls'), name='home'),
    path(r'profile/<slug:link>/', profile_view, name='profile'),
    #path(r'profile/<slug:link>/get/', getProfilePosts, name='profile-posts'),
    path(r'messenger/', include('messenger.urls'), name='messenger'),
    path(r'notifications/', include('notifications.urls'), name='notifications'),
]

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),]

messenger/urls.py
from django.urls import path
from .views import *

app_name = 'messenger'
urlpatterns = [
    path(r'<str:link>/', chat_view, name='chat'),
    path(r'', chat_view, name='empty-chat'),
    path(r'<str:link>/send/', user_send_message_ajax, name='send'),
    path(r'<str:link>/get/', user_receiver_message_ajax, name='get-messages'),
]

notifications/urls.py
from django.urls import path
from . import views

app_name = 'notifications'
urlpatterns = [
    path(r'', views.notifications_view, name='index'),
    path(r'delete/<slug:id>/', views.delete_notification_ajax, name='delete-notification'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path(r'', views.home_view, name='home'),
    path(r'createpost/', views.create_post_view, name='add-post'),
    path(r'post/<int:post_id>/', views.view_post_view, name='view-post'),
    path(r'update/<int:post_id>/', views.update_post_view, name='update'),
    # path(r'like/<int:post_id>/', views.like_post_view, name='like-post'),
    # path(r'unlike/<int:post_id>/', views.unlike_post_view, name='unlike-post'),
    path(r'comment/<int:post_id>/', views.add_comment_view, name='add-comment'),
    path(r'search/', views.search_view, name='search'),
    path(r'share/<int:post_id>/', views.share_post_view, name='share-post'),
    
    #ajax
    path(r'ajax-like/<int:post_id>/', views.like_post_ajax, name='like-post-ajax'),
    path(r'ajax-unlike/<int:post_id>/', views.unlike_post_ajax, name='unlike-post-ajax'),
    path(r'ajax-comment/<int:post_id>/', views.add_comment_ajax, name='add-comment-ajax'),
    path(r'delete/<int:post_id>/', views.delete_post_ajax, name='delete'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'logout/', views.logout_view, name='logout'),
    path(r'login/', views.login_with_limit_view, name='login'),
    path(r'register/', views.register_view, name='register'),
    path(r'account-settings/', views.account_settings_view, name='account-settings'),
    path(r'delete-account/', views.delete_account_view, name='delete'),
    path(r'delete-profile-picture/', views.delete_profile_picture_view, name='delete-profile-picture'),
    path(r'delete-profile-cover/', views.delete_profile_cover_view, name='delete-profile-cover'),
    path(r'activate/<uidb64>/<token>/', views.activate_view, name='activate'),
    path(r'personal-settings/', views.personal_settings_view, name='personal-settings'),
    path(r'send-friend-request/<slug:link>/', views.send_friend_request_view, name='add-friend'),
    path(r'accept-friend-request/<slug:link>/', views.accept_friend_request_view, name='create-friend'),
    path(r'decline-friend-request/<slug:link>/', views.decline_friend_request_view, name='decline-friend'),
    path(r'unfriend/<slug:link>/', views.unfriend_view, name='unfriend'),
    path(r'cancel-friend-request/<slug:link>/', views.cancel_friend_request_view, name='cancel-friend'),
    path(r'forgot-password/', views.forgot_password_view, name='forgot-password'),   
    path(r'friends/', views.show_all_friends_view, name='friend-list'),
]

notifications/models.py
from django.db import models
from django.contrib.auth import get_user_model as User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db.models.constraints import UniqueConstraint
# Create your models here.


class Notification(models.Model):
    # class Meta:
    #     constraints = [
    #         UniqueConstraint(fields=['route_id', 'type', 'user_from'], name='notification_uniqueness_constraint')
    #     ]

    user_from = models.ForeignKey(to=User(), on_delete=models.CASCADE, related_name='notification_from')
    user_to = models.ForeignKey(to=User(), on_delete=models.SET_NULL, related_name='notification_to', null=True)
    content = models.CharField(max_length=200, blank=False, null=False, )
    
    choices = [('C', 'Comment'), ('L', 'Like'), ('F', 'Friend'), ]
    type = models.CharField(choices=choices, max_length=1, null=False, blank=False,)
    picture = models.ImageField(default='profile_pics/default.jpg')
    date = models.DateTimeField(auto_now_add=True)
    route_id = models.SlugField(default=None)
    seen = models.BooleanField(default=False)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True)
    object_id = models.PositiveIntegerField(null=True)
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return f"{self.user_to} notification"

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model as User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

class Post(models.Model):
    post_content = models.TextField(blank=True)
    creator = models.ForeignKey(User(), on_delete=models.CASCADE)
    create_date = models.DateTimeField(default=timezone.now)
    likes = models.IntegerField(default=0)
    comments = models.IntegerField(default=0)
    image = models.ImageField(default='', blank=True, upload_to='posts_pics')
    shared_post = models.BooleanField(default=False)
    original_post = models.ForeignKey(to='self', on_delete=models.SET_NULL, null=True, blank=True)

    def clean(self, *args, **kwargs) -> None:
        if self.shared_post and self.image != '':
            raise ValidationError(_("Shared post cannot have an image"), code="image-shared-post")
        if self.post_content == '' and not self.shared_post:
            raise ValidationError(_("non-shared posts cannot have no content"), code="shared-post-no-content")
        if self.original_post != None and self.shared_post == False:
            raise ValidationError(_("non-shared posts cannot have reference to any posts"), code="non-shared-post-reference")
        if self.shared_post and self.original_post == self:
            raise ValidationError(_("shared posts cannot reference themselves"), code="self-referencing")
        return super().clean(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)
    
    def __str__(self):
        string = self.post_content[0:30]
        if len(string) == 30:
            string += "..."
        return f"{string}, Post ID: {self.id} from: {self.creator}"

class Comment(models.Model):
    comment_content = models.CharField(max_length=1000)
    creator = models.ForeignKey(User(), on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    create_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        comment = self.comment_content[0:10]
        if len(comment) > 10:
            comment += "..."
        return f"{comment}, Comment ID: {self.id} from: {self.creator} to post: {self.post}"

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    liker = models.ForeignKey(User(), on_delete=models.CASCADE)

    @staticmethod
    def is_post_liked_by_user(user: User(), post: Post):
        return Like.objects.filter(liker=user, post=post).exists()
    
    def __str__(self):
        return f"Like ID: {self.id} On Post: {self.post.id} from: {self.liker.username}"

notifications/views.py
from django.http.response import HttpResponseNotAllowed, JsonResponse
from django.shortcuts import redirect, render
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth import get_user_model as User

from .models import Notification
from users.models import Friend
# Create your views here.

def notifications_view(request):
    if request.user.is_authenticated:
        notifications = Notification.objects.filter(user_to=request.user).order_by('-date')[0:10]
        context = {
            'notifications': notifications,
            'active_user': User().objects.select_related('profile').get(pk=request.user.pk)
        }
        for notification in notifications:
            notification.seen = True
            notification.save()
        return render(request, 'pages/NewNotifications.html', context)
    else:
        messages.error(request, "you need to login first")
        return redirect('users:index')

def delete_notification_ajax(request, id):
    if request.user.is_authenticated:
        notification = Notification.objects.filter(id=id).first()
        if notification:
            if notification.type == 'F':
                link = notification.route_id
                sender = User().objects.filter(profile__link=link).first()
                if sender:
                    friendship = Friend.objects.filter((Q(side1=sender) & Q(side2=request.user)) | (Q(side1=request.user) & Q(side2=sender))).first()
                    if friendship and friendship.accepted == False:
                        friendship.delete()
                    else:
                        messages.error(request, "no such friend request to decline")
                        return JsonResponse({"message":"no-friend"})
            if notification.user_to == request.user:
                notification.delete()
            else:
                return HttpResponseNotAllowed(['POST', 'GET'])
            return JsonResponse({"message":"good"})
        else:
            return JsonResponse({"message":"no-notification"})
    else:
        messages.error(request, "you need to login first")
        return redirect('users:index')

pages/templates/pages/deprecated/Chat.html
{% extends 'pages/BaseChat.html' %}
{% load static %}
{% block head %}
    <title>
        {% if his_username %}
            {{his_username}}
        {% else %}
            chat
        {% endif %}
    </title>
    <!-- <link rel="stylesheet" href="{% static 'pages/css/chat.css'%}"> -->
{% endblock head %}

{% block header %}
<a href="{% url 'posts:home' %}">Home</a>
{% endblock %}

{% block content %}
    <div id="friends-list">
        <ul>
            {% for friend in friends %}
                <li><a href="{% url 'messenger:chat' friend.profile.link %}">{{ friend.profile.name }}</a></li>
            {% endfor %}
        </ul>
    </div> 
    <div>
        {% if unseen_messages > 0 %}
        <p>You have {{unseen_messages}} new message !</p>
        {% endif %}
    </div>
    <div>
        <fieldset class="fieldset-auto-width">
            <legend>
                {% if his_username %}
                    {{his_username}}
                {% else %}
                    chat
                {% endif %}
            </legend>
            <ul id="chat">
                {% for message in chat %}
                    <li>
                        <p>{{ message.sender.first_name }}: {{ message.message_content }}</p>
                        <small>{{ message.send_date }}</small>
                    </li>
                {% endfor %}
            </ul>
        </fieldset>
    </div>
    {% if his_link %}
        <form id="post-form">
            {%csrf_token%}
            <!-- <textarea name="chat-input" id="chat-input" cols="30" rows="10"></textarea> -->
            {{ form.as_p }}
            <input id='send' type="submit" value="Send">
        </form>
    {% endif %}

    {% if his_link %}
    <script type="text/javascript">
        var postForm = document.getElementById("post-form");
        var messageInput = document.getElementById("{{form.message_input.id_for_label}}");
        var chat = document.getElementById("chat");

        postForm.addEventListener("submit", sendFunction);

        function sendFunction(event)
        {
            // stopping the default submit
            event.preventDefault();

            // creating new XHR
            var xhr = new XMLHttpRequest();
            
            // get the message 
            var message = messageInput.value;
            var csrf = document.getElementsByName("csrfmiddlewaretoken")[0].value;
            var params = "message_input="+message +"&csrfmiddlewaretoken="+csrf;
            xhr.open("POST", "{% url 'messenger:send' his_link %}", true);
            xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            
            xhr.onload = function()
            {
                if(this.status == 200)
                {
                    var response = JSON.parse(this.responseText);
                    const list = document.createElement("li");
                    const paragraph = document.createElement("p");
                    const small = document.createElement("small");
                    list.appendChild(paragraph);
                    list.appendChild(small);
                    paragraph.innerHTML = response.sender + ": " + response.content;
                    small.innerHTML = response.time;

                    chat.appendChild(list);
                    messageInput.value = "";
                }
            }
            xhr.send(params);
        }

        var worker = new Worker("{% static 'pages/js/chatjs/check_new_messages.js'%}");
        (function(){
            var f = function() {
                worker.postMessage("{% url 'messenger:get-messages' his_link %}")
            };
            window.setInterval(f, 10000);
            f();
        })();
        worker.onmessage = function(e)
        {
            var response = JSON.parse(e.data);
            var i = 0;
            while(response[i] != undefined)
            {
                const list = document.createElement("li");
                const paragraph = document.createElement("p");
                const small = document.createElement("small");
                list.appendChild(paragraph);
                list.appendChild(small);
                paragraph.innerHTML = response[i].sender + ": " + response[i].message_content;
                small.innerHTML = response[i].send_date;

                chat.appendChild(list);
                i += 1;
            }
        }
    </script>
    {% endif %}
{% endblock %}

pages/templates/pages/deprecated/Profile.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
	<head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"> 
        <meta charset="utf-8">
        <title>Profile Page</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="{% static 'pages/fonts/fontawesome-free-5.15.3-web/css/all.css'%}" rel="stylesheet">
        <link href="{% static 'pages/css/bootstrap.css'%}" rel="stylesheet">
        <!--[if lt IE 9]>
          <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <link href="{% static 'pages/css/profile.css'%}" rel="stylesheet">
    </head>
    
    <body>
		
        <div class="wrapper">
			<div class="box">
				<!-- top nav -->
				<div class="navbar navbar-blue navbar-static-top" style="width: 100%;">  
					<div class="navbar-header">
						<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						</button>
						<a href="{% url 'users:index' %}" class="navbar-brand logo">F</a>
					</div>
					<nav class="collapse navbar-collapse" role="navigation">
					<form class="navbar-form navbar-left" method="GET" action="{% url 'posts:search' %}">
						<div class="input-group input-group-sm" style="max-width:360px;">
							<input class="form-control" placeholder="Search" name="search-text" id="srch-term" type="text">
							<div class="input-group-btn">
							<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
							</div>
						</div>
					</form>
					<ul class="nav navbar-nav">
						<li>
						<a href="{%url 'posts:home'%}"><i class="glyphicon glyphicon-home"></i> Home</a>
						</li>
						<li>
						<a href="{% url 'messenger:empty-chat' %}"><i class="fab fa-rocketchat"></i> Chat</a>
						</li>
						<li>
						<a href="{% url 'profile' my_profile_link %}"><img src="{{myProfilePicture.url}}" class="img-circle pull-left" style="width: 40px;height: 40px; margin-top: -10px;"><span class="badge">{{navbar_name}}</span></a>
						</li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fas fa-caret-square-down fa-lg"></i></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'users:account-settings'%}"><i class="fas fa-cog"></i> Settings</a></li>
							<li><a href="{% url 'messenger:empty-chat'%}"><i class="fab fa-rocketchat"></i> Chat</a></li>
							<li><a href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt"></i> Log Out</a></li>
							<!--<li><a href="">More</a></li>
							<li><a href="">More</a></li>
							<li><a href="">More</a></li> -->
						</ul>
						</li>
					</ul>
					</nav>
				</div>
				<!-- /top nav -->
										
				<div class="row row-offcanvas row-offcanvas-left">
					
					<!-- sidebar -->
					<div class="column col-sm-2 col-xs-1 sidebar-offcanvas" id="sidebar">
					  
						<ul class="nav">
							<li><a href="#" data-toggle="offcanvas" class="visible-xs text-center"><i class="glyphicon glyphicon-chevron-right"></i></a></li>
						</ul>
					   
						<ul class="nav hidden-xs" id="lg-menu">
							<li class="active"><a href=""><i class="glyphicon glyphicon-refresh"></i> Refresh</a></li>
							<li><a href="#"><i class="glyphicon glyphicon-list"></i> Stories</a></li>
							<li><a href="#"><i class="fas fa-user-friends"></i> Friends</a></li>
							<li><a href="#"><i class="fas fa-history"></i> Memories</a></li>
							<li><a href="#"><i class="fas fa-bookmark"></i> Saved</a></li>
							<li><a href="#"><i class="fas fa-users"></i> Groups</a></li>										
						</ul>
						<ul class="list-unstyled hidden-xs" id="sidebar-footer">
							<li>
							 <p style="font-size: 11px;">Privacy· Terms· Advertising· <br>Ad Choices <i class="fas fa-angle-double-right"></i>· Cookies· More· Facepage © 2021</p>
							</li>
						</ul>
					  
						<!-- tiny only nav-->
					  <ul class="nav visible-xs" id="xs-menu">
						    <li><a href="" class="text-center"><i class="glyphicon glyphicon-refresh"></i></a></li>
							<li><a href="#" class="text-center"><i class="glyphicon glyphicon-list"></i></a></li>
							<li><a href="#" class="text-center"><i class="fas fa-user-friends"></i></a></li>
							<li><a href="#" class="text-center"><i class="fas fa-history"></i></a></li>
							<li><a href="#" class="text-center"><i class="fas fa-bookmark"></i></a></li>
							<li><a href="#" class="text-center"><i class="fas fa-users"></i></a></li>
						
						</ul>
					  
					</div>
					<!-- /sidebar -->
				  
					<!-- main right col -->
					<div class="column col-sm-10 col-xs-11" id="main">
              
							
							
						
									<div class="card hovercard">
										<div class="cardheader" style="background: url('{{profile_cover.url}}');background-size: cover;height: 300px;">
						
										</div>
										<div class="avatar">
											<img alt="" src="{{profile_pic.url}}">		
											<!-- <button style="margin-right: -40px; margin-left: -4px; display: inline-block;"><i class="fas fa-camera"></i></button>-->
										</div>
										
										<div class="info">
											<div class="title">
												<a href="{%url 'profile' profile_link %}">{{profile_name}}</a>
											</div>
											<div class="desc">{{bio}}</div>
										</div>
								
									</div>
						<hr>
							
						
						
						<div class="padding">
						
							<div class="full col-sm-9" >
							
							        
								<!-- content -->                      
								<div class="row">
							
								 <!-- main col left --> 
								 <div class="col-sm-5">
								   
									<!-- <div class="well"> 
										<form class="form-horizontal" role="form">
										<h4>What's New</h4>
											<div class="form-group" style="padding:14px;">
											<textarea class="form-control" placeholder="What's on your mind?"></textarea>
										</div>
										<button class="btn btn-primary pull-right" type="button">Post</button><ul class="list-inline"><li><a href=""><i class="fas fa-photo-video"></i></a></li><li><a href=""><i class="fas fa-user-tag"></i></a></li><li><a href=""><i class="glyphicon glyphicon-map-marker"></i></a></li></ul>
										</form>
									</div> -->
									{% for post in page_obj %}
										<div class="panel panel-default">
										<div class="panel-heading" >
											<img src="{{ post.creator.profile.profile_picture.url }}" class="img-circle pull-left">
											{% if my_profile_link == profile_link %}
												
												<a href="{% url 'posts:delete' post.id %}"><button type="submit" class="pull-right"><i class="fas fa-trash-alt"></i></button></a>
												
													
												<a href="{% url 'posts:update' post.id %}"><button type="submit" class="pull-right"><i class="fas fa-edit"></i></button></a>
												
											{% endif %}
											<h4 style="font-size: 17px; font-weight: bold;"><a href="{% url 'profile' post.creator.profile.link %}">{{ post.creator.first_name }} {{post.creator.last_name}}</a><br>
											<p style="font-size: 13.5px; font-weight: lighter;">{{ post.create_date|naturaltime }}. <i class="fas fa-globe-americas" style="font-size: 13px;"></i></p>
										</h4>
										</div>
											<div class="panel-body">
								
											<p>{{ post.post_content }}</p>
											
											<!-- <hr>
											<div class="panel-thumbnail"><img src="{% static 'pages/img/bg_5.jpg'%}" class="img-responsive"></div> -->
											<div class="clearfix"></div>
											<hr>
											<div class="input-group">
												<div class="input-group-btn">
													{% if post in liked_posts %}
														<form action="{% url 'posts:unlike-post' post.id %}" method="GET"> {%csrf_token%}
															<button class="btn btn-default"><i class="fas fa-thumbs-down"></i> {{ post.likes }}</button>
														</form>
													{% else %}
													<form action="{% url 'posts:like-post' post.id %}" method="GET"> {%csrf_token%}
														<button class="btn btn-default"><i class="fas fa-thumbs-up"></i> {{ post.likes }}</button>
													</form>
													{% endif%}
												</div>
												<form action="{% url 'posts:add-comment' post.id %}" method="get"> {%csrf_token%}
													<input name="comment-content" class="form-control" placeholder="Add a comment.." type="text">
												</form>
											</div>
											{% for comment in post.comment_set.all %}
												<div class="panel-heading" style="background-color: lightgrey; margin-bottom: 20px;">
													<img src="{{comment.creator.profile.profile_picture.url}}" class="img-circle pull-left">
													<h4 style="font-size: 15px; font-weight: bold;">{{comment.creator.first_name}} {{comment.creator.last_name}}<br>
													<p style="font-size: 13.5px; font-weight: 300;">
														{{comment.comment_content}}
													</p></h4>
												</div>
												{% endfor %}
											
											</div>
										</div>
									{% endfor %}
  							     </div>
								  
						
							   </div><!--/row-->

							<div class="container" style="width:100%; text-align:center;">
								{% if page_obj.number != 1 %}
									<a href="?page={{ page_obj.previous_page_number }}" id="nexPrev" class="previous round">&#8249;</a>
								{% endif %}
								{% if page_obj.number != page_obj.paginator.num_pages %}	
									<a href="?page={{ page_obj.next_page_number }}" id="nexPrev" class="next round">&#8250;</a>
								{% endif %}
							</div>


							   <hr>
							   <h4 class="text-center">
								<p style="font-size: 11px;">Privacy· Terms· Advertising· Ad Choices <i class="fas fa-angle-double-right"></i>· Cookies· More· Facepage © 2021</p>
							   </h4>
							   <hr>
						
								
							  
							</div><!-- /col-9 -->
						</div><!-- /padding -->
					</div>
					<!-- /main -->
				  
				</div>
			</div>
		</div>


        
        <script type="text/javascript" src="{% static 'pages/js/jquery.js'%}"></script>
        <script type="text/javascript" src="{% static 'pages/js/bootstrap.js'%}"></script>
</body></html>

pages/templates/pages/deprecated/VerificationSent.html
{% extends 'pages/BaseUsers.html' %}

{% block body %}
    <a href="{% url 'users:index'%}">Home</a>
    <h1>Verify your E-mail</h1>
    <p>A confirmation link has been sent to your E-mail, please check your E-mail.</p>
{% endblock body %}

pages/templates/pages/deprecated/originalHome.html
{% extends 'pages/base.html' %}

{% block title %}
Facepage
{% endblock title %}

{% block header %}
    <h3>Hello: <a href="{% url 'profile' name %}">{{name}}</a></h3>
    <a href="{% url 'posts:home'%}">Home</a>
    <form action="{% url 'users:logout' %}" method="POST"> {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
    <form action="{% url 'posts:search' %}" method="GET">
        <input type="text" name="search-text" id="search_content">
        <input type="submit" value="Search">
    </form>
    <div><a href="{% url 'users:settings' %}">Settings</a></div>
    <div><a href="{% url 'messenger:empty-chat' %}">Chat</a></div>
{% endblock header %}
{% block content %}
    {% if my_last_post %}
    <div>
        <p><strong>Your latest post:</strong></p>
        <p>{{ my_last_post.post_content }}</p>
        <p>{{ my_last_post.create_date }}</p>
        <p>Likes: {{ my_last_post.likes }}</p>
        <p>Comments: {{my_last_post.comments}}</p>
    </div>
    {% else %}
    <div>
        <p>You dont have any posts</p>
    </div>
    {% endif %}
    <form action="{% url 'posts:add-post' %}" method="post"> {% csrf_token %}
        <textarea name="new-post-content" id="" cols="30" rows="10"></textarea>
        <input type="submit" value="Add post">
    </form>
    <br>
    <p><strong>Latest from friends</strong></p>
    {% for post_query in friends_posts %}
        {% for post in post_query %}
            <div>
                <p><a href="{% url 'profile' post.creator %}">{{ post.creator }}</a></p>
                <p>{{ post.post_content }}</p>
                <p>{{ post.create_date }}</p>
                <p>Likes: {{ post.likes }}</p>
                <p>Comments: {{post.comments}}</p>
                {% if post.comments != 0%}
                <div>
                    <h4>Comments:</h4>
                    {% for comment in post.comment_set.all %}
                        <p>{{comment.creator}}: {{comment.comment_content}}</p>
                        <p>{{comment.create_date}}</p>
                    {% endfor %}
                </div>
                {% endif %}
                <div class="actions">
                    <div class="like">
                        {% if post in liked_posts %}
                            <p>You liked this post</p>
                        {% else %}
                        <form action="{% url 'posts:like-post' post.id %}" method="GET"> {%csrf_token%}
                            <input type="submit" value="Like">
                        </form>
                        {% endif %}
                    </div>
                    <div class="comment">
                        <form action="{% url 'posts:add-comment' post.id %}" method='GET'> {%csrf_token%}
                            <input type="text" name="comment-content">
                            <input type="submit" value="Add comment">
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endfor %}
{% endblock content %}