facepage/urls.py
#from posts.views import getProfilePosts
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from posts.views import profile_view

urlpatterns = [
    path(r'admin/', admin.site.urls, name='admin'),
    path(r'', include('users.urls'), name='users'),
    path(r'home/', include('posts.urls'), name='home'),
    path(r'profile/<slug:link>/', profile_view, name='profile'),
    #path(r'profile/<slug:link>/get/', getProfilePosts, name='profile-posts'),
    path(r'messenger/', include('messenger.urls'), name='messenger'),
    path(r'notifications/', include('notifications.urls'), name='notifications'),
]

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),]

messenger/urls.py
from django.urls import path
from .views import *

app_name = 'messenger'
urlpatterns = [
    path(r'<str:link>/', chat_view, name='chat'),
    path(r'', chat_view, name='empty-chat'),
    path(r'<str:link>/send/', user_send_message_ajax, name='send'),
    path(r'<str:link>/get/', user_receiver_message_ajax, name='get-messages'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path(r'', views.home_view, name='home'),
    path(r'createpost/', views.create_post_view, name='add-post'),
    path(r'post/<int:post_id>/', views.view_post_view, name='view-post'),
    path(r'update/<int:post_id>/', views.update_post_view, name='update'),
    # path(r'like/<int:post_id>/', views.like_post_view, name='like-post'),
    # path(r'unlike/<int:post_id>/', views.unlike_post_view, name='unlike-post'),
    path(r'comment/<int:post_id>/', views.add_comment_view, name='add-comment'),
    path(r'search/', views.search_view, name='search'),
    path(r'share/<int:post_id>/', views.share_post_view, name='share-post'),
    
    #ajax
    path(r'ajax-like/<int:post_id>/', views.like_post_ajax, name='like-post-ajax'),
    path(r'ajax-unlike/<int:post_id>/', views.unlike_post_ajax, name='unlike-post-ajax'),
    path(r'ajax-comment/<int:post_id>/', views.add_comment_ajax, name='add-comment-ajax'),
    path(r'delete/<int:post_id>/', views.delete_post_ajax, name='delete'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'logout/', views.logout_view, name='logout'),
    path(r'login/', views.login_with_limit_view, name='login'),
    path(r'register/', views.register_view, name='register'),
    path(r'account-settings/', views.account_settings_view, name='account-settings'),
    path(r'delete-account/', views.delete_account_view, name='delete'),
    path(r'delete-profile-picture/', views.delete_profile_picture_view, name='delete-profile-picture'),
    path(r'delete-profile-cover/', views.delete_profile_cover_view, name='delete-profile-cover'),
    path(r'activate/<uidb64>/<token>/', views.activate_view, name='activate'),
    path(r'personal-settings/', views.personal_settings_view, name='personal-settings'),
    path(r'send-friend-request/<slug:link>/', views.send_friend_request_view, name='add-friend'),
    path(r'accept-friend-request/<slug:link>/', views.accept_friend_request_view, name='create-friend'),
    path(r'decline-friend-request/<slug:link>/', views.decline_friend_request_view, name='decline-friend'),
    path(r'unfriend/<slug:link>/', views.unfriend_view, name='unfriend'),
    path(r'cancel-friend-request/<slug:link>/', views.cancel_friend_request_view, name='cancel-friend'),
    path(r'forgot-password/', views.forgot_password_view, name='forgot-password'),   
    path(r'friends/', views.show_all_friends_view, name='friend-list'),
]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model as User
from django.core.validators import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import Profile
from typing import Dict, Any

class DeleteAccountForm(forms.Form):
    username = forms.CharField(max_length=100, label='Your username', required=True)
    confirmation = forms.CharField(widget=forms.Textarea, label='Confirmation', required=True)


class ChangePictureBioForm(forms.ModelForm):
    first_name = forms.CharField(max_length=150, label='First name', required=False)
    last_name = forms.CharField(max_length=150, label='Last name', required=False)
    class Meta:
        model = Profile
        fields = ['bio', 'profile_picture', 'profile_cover', 'phone_number', 'gender', 'birthday']
        widgets = {
            'bio': forms.Textarea(),
        }

class RegisterForm(UserCreationForm):
    birthday = forms.DateField(widget=forms.DateInput())
    gender = forms.ChoiceField(widget=forms.RadioSelect, choices=[('M', 'Male'), ('F', 'Female')])

    class Meta:
        model = User()
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']

users/views.py
from django.db.models import Q
from django.http.response import JsonResponse
from django.http import HttpResponseRedirect, HttpRequest
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.contrib.auth.password_validation import validate_password
from django.contrib.auth import get_user_model as User
from django.conf import settings
from django.utils import timezone
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.utils.translation import gettext as _

from django.core.exceptions import ValidationError
from django.core.validators import validate_email

from .forms import DeleteAccountForm, ChangePictureBioForm, RegisterForm
from .models import Friend, Profile, SendEmailRequest, NewAccountActivationLink, FriendRequest

from .signals import create_activation_link_signal, create_profile_signal
from notifications.models import Notification
from notifications.signals import send_friend_request_signal
import json

from .utils.utils import create_user_link, send_activate_email, send_new_password
from .utils.id_generator import generate_random_characters, generator_letters, id_generator
from .utils.tokens import account_activation_token

from django.views.decorators.csrf import ensure_csrf_cookie
from .utils.constants import FIVE_MINUTES


def index(request: HttpRequest):
    """
    view the login page or redirects to the home page if you are already logged in
    """
    if request.user.is_authenticated:
        return redirect('posts:home')
    
    return render(request, 'pages/Login.html')


def login_with_limit_view(request: HttpRequest):
    """
    Login view function, it prevents logging more than 3 times 
    """
    if request.user.is_authenticated:
        return redirect("index")
    if request.method == "POST":
        if not can_login_again(request):
            messages.error(request, "Please wait some time before logging again")
            return redirect("users:index")
        username = request.POST.get("username")
        password = request.POST.get("pass")
        if (user := authenticate(username=username, password=password)) is not None:
            if Profile.objects.get(user=user).verified == False:
                if not SendEmailRequest.objects.get_or_create(user=user)[0].is_still_soon():
                    send_activate_email(request, user, True)
                    messages.warning(request,"Your account is not verified, check your email for the activation link")
                else:
                    messages.warning(request,
                    """
                    Your account is not activated, and cannot send an activation link to you right now, try again later
                    """.strip()
                    )
            else:
                clear_login_attempts_data_from_session(request)
                login(request, user)
        else:
            messages.error(request, "Wrong username or password, please try again")
    return redirect('users:index')

def can_login_again(request: HttpRequest) -> bool:
    """
    if the user tried to login with wrong credentials more
    than 3 times this function returns false
    and this user has to wait five mimutes to login again

    returns true if the user entered credentials less than 3 or
    if the user waited for the five minutes after the third attempt

    """
    
    if request.session.get('last_login_attempt') is None:
        request.session['last_login_attempt'] = timezone.localtime(timezone.now()).strftime("%c")
    if (x := request.session.get("login_attempts")) == None:
        request.session['login_attempts'] = 1
        return True
    request.session['login_attempts'] += 1
    if x < 3:
        return True
    last_loggin_attempt_from_session = timezone.datetime.strptime(request.session.get("last_login_attempt"), "%c")
    last_logging_attempt_from_session_aware = timezone.make_aware(last_loggin_attempt_from_session)
    time_after_last_login_attempt = (timezone.localtime(timezone.now()) - last_logging_attempt_from_session_aware).total_seconds()
    if time_after_last_login_attempt > FIVE_MINUTES:
        request.session['last_login_attempt'] = timezone.localtime(timezone.now()).strftime("%c")
        return True
    else:
        return False


def clear_login_attempts_data_from_session(request: HttpRequest) -> None:
    """
    Clear the login_attempts and last_login_attempt variables in
    request.session
    """
    try:
        del request.session['login_attempts']
        del request.session['last_login_attempt']
    except KeyError:
        return


def logout_view(request: HttpRequest):
    logout(request)
    messages.success(request, "You have been logged out")
    return redirect('users:index')


def forgot_password_view(request: HttpRequest):
    if request.method == "POST":
        email = request.POST.get("email")
        try:
            validate_email(email)
        except ValidationError as error:
            return JsonResponse({"message": error.messages})
        if (requester := User().objects.filter(email=email).first()) == None:
            return JsonResponse({"message": "no user"})
        forget_password_request = SendEmailRequest.objects.get_or_create(user=requester)[0]
        if forget_password_request.is_still_soon():
            return JsonResponse({"message": "time limit"})
        new_password = generate_random_characters(10, generator_letters())
        requester.set_password(new_password)
        requester.save()
        try:
            send_new_password(new_password, email)
            forget_password_request.last_request = timezone.localtime(timezone.now())
            forget_password_request.save()
        except Exception as e:
            return JsonResponse({'message': e.__str__()})
        return JsonResponse({'message':'good'})
    else:
        return render(request, 'pages/ForgotPassword.html')


@ensure_csrf_cookie
def register_view(request: HttpRequest):
    """
    UNDER DEVELOPMENT
    Register view that creates profile and
    activation link using signals
    """
    if request.user.is_authenticated:
        return redirect('users:index')
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            new_link = create_user_link(user)
            create_profile_signal.send(
                sender=User(),
                user=user,
                link=new_link,
                birthday= form.cleaned_data['birthday'],
                gender= form.cleaned_data['gender'],
            )
            send_email_success, uid, token = send_activate_email(request, user, True)
            if not send_email_success:
                user.delete()
                return JsonResponse({"message": "email not send"})
            create_activation_link_signal.send(
                sender=User(),
                user=user,
                activation_link= f"{uid}/{token}"
            )
            return JsonResponse({'message':'good'})
        else:
            return JsonResponse(json.loads(form.errors.as_json()))
    else:
        form = RegisterForm()
    return render(request, 'pages/Register.html', {'form':form})

@login_required
def send_friend_request_view(request: HttpRequest, link: str):
    user = get_object_or_404(User(), profile__link=link)
    is_there_friendship = Friend.objects.filter(((Q(side1=request.user) & Q(side2=user)) | (Q(side1=user) & Q(side2=request.user)))).exists()

    if is_there_friendship:
        messages.error(request, "you are already friends")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    if (friend_request := FriendRequest.objects.filter(Q(user_from=request.user) & Q(user_to=user))).exists():
        if friend_request.first().status == FriendRequest.FRIEND_REQUEST_DECLINED:
            if friend_request.first().user_from == user:
                friend_request.first().status = FriendRequest.FRIEND_REQUEST_WAITING
                friend_request.first().save()
            else:
                messages.success(request, "cannot accept friend request right now")
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            messages.success(request, "friend request already sent")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        new_friend_request = FriendRequest(user_from=request.user, user_to=user)
        new_friend_request.save()
    notification_content = f"{request.user.profile.name()} sent you a friend request"
    send_friend_request_signal.send(
        sender=User(), 
        user_from=request.user,
        user_to=user,
        content=notification_content,
        type='F',
        picture=request.user.profile.profile_picture.url,
        content_object=new_friend_request,
        route_id=request.user.profile.link,
    )
    messages.success(request, "friend request sent")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def accept_friend_request_view(request: HttpRequest, link: str):
    sender = User().objects.filter(profile__link=link).first()
    if not sender:
        messages.error(request, "no such user")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    friend_request = FriendRequest.objects.filter(user_from=sender, user_to=request.user).first()
    if not friend_request:
        messages.error(request, "no such friend request to accept")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    if friend_request.status == FriendRequest.FRIEND_REQUEST_ACCEPTED:
        messages.success(request, "you are already friends")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

users/templates/users/OriginalIndex.html
<html>
    <head>
        {% block head %}
            <title>
            {% block title %}
                Facepage
            {% endblock title %}
            </title>
        {% endblock head %}
    </head>
    <body>
        {% block body %}
            <header>
                {% block header %}
                <h1>Welcome to facepage</h1>
                {% endblock header %}
            </header>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}
                {% if message %}<p><strong>{{message }}</strong></p>{% endif %}
                    <form action="{% url 'users:login' %}" method="POST"> {% csrf_token %}
                        <fieldset>
                            <legend>Log in</legend>
                            <label for="username">Username</label>
                            <input type="text" name="username" id="username">
                            <br>
                            <label for="password">Password</label>
                            <input type="password" name="password" id="password">
                            <br>
                            <input type="submit" value="Login">
                        </fieldset>
                    </form>
                <small>Need an account ? <a href="{% url 'users:register' %}">Register</a></small>
            {% endblock content %}
            <footer>
                {% block footer%}
                {% endblock footer %}
            </footer>
        {% endblock body %}
    </body>
</html>

users/templates/users/acc_activate.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

users/templates/users/accountSettings.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"> 
        <meta charset="utf-8">
        <title>Settings</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="{% static 'users/fonts/fontawesome-free-5.15.3-web/css/all.css'%}" rel="stylesheet">
        <link href="{% static 'users/css/bootstrap.css'%}" rel="stylesheet">
        <!--[if lt IE 9]>
          <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <link href="{% static 'users/css/facebook.css'%}" rel="stylesheet">
		<style>
			
			
			.testbox {
			display: flex;
			justify-content: center;
			align-items: center;
			height: inherit;
			padding: 3px;
			}
			
			input, select, textarea {
			margin-bottom: 10px;
			border: 1px solid #ccc;
			border-radius: 3px;
			}
			input {
			width: calc(100% - 10px);
			padding: 5px;
			}
			select {
			padding: 7px 0;
			background: transparent;
			}
			textarea {
			width: calc(100% - 6px);
			}
			.item {
			position: relative;
			margin: 10px 0;
			}
			.item:hover p{
			color: #095484;
			}
			.item:hover i{
				color: red;
			}
			input:hover, select:hover, textarea:hover {
			box-shadow: 0 0 5px 0 #095484;
			}
			input[type="date"]::-webkit-inner-spin-button {
			display: none;
			}
			input[type="time"]::-webkit-inner-spin-button {
			margin: 2px 22px 0 0;
			}
		
			[type="date"]::-webkit-calendar-picker-indicator {
			right: 0;
			z-index: 2;
			opacity: 0;
			cursor: pointer;
			}
			.btn-block {
			margin-top: 20px;
			text-align: center;
			}
			.buttonS {
			width: auto;
			padding: 10px;
			border: none;
			-webkit-border-radius: 5px; 
			-moz-border-radius: 5px; 
			border-radius: 5px; 
			background-color: #095484;
			font-size: 10px;
			color: #fff;
			cursor: pointer;
			}
			.buttonS:hover {
			background-color: #0666a3;
			}
			@media (min-width: 568px) {
			.name-item, .city-item {
			display: flex;
			flex-wrap: wrap;
			justify-content: space-between;
			}
			.name-item input{
			width: calc(50% - 20px);
			}

			}
		  </style>
    </head>
    
    <body>
        
        <div class="wrapper">
			<div class="box">
				<!-- top nav -->
				<div class="navbar navbar-blue navbar-static-top" style="width: 100%;">  
					<div class="navbar-header">
						<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						</button>
						<a href="" class="navbar-brand logo">F</a>
					</div>
					<nav class="collapse navbar-collapse" role="navigation">
					<form class="navbar-form navbar-left" method="GET" action="{% url 'posts:search' %}">
						<div class="input-group input-group-sm" style="max-width:360px;">
							<input class="form-control" placeholder="Search" name="search-text" id="srch-term" type="text">
							<div class="input-group-btn">
							<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
							</div>
						</div>
					</form>
					<ul class="nav navbar-nav">
						<li>
						<a href="{% url 'posts:home' %}"><i class="glyphicon glyphicon-home"></i> Home</a>
						</li>
						<li>
						<a href="{% url 'messenger:empty-chat' %}"><i class="fab fa-rocketchat"></i> Chat</a>
						</li>
						<li>
						<a href="{% url 'profile' username %}"><img src="{{profile_pic}}" class="img-circle pull-left" style="width: 40px;height: 40px; margin-top: -10px;"><span class="badge">{{username}}</span></a>
						</li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fas fa-caret-square-down fa-lg"></i></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'users:account-settings'%}"><i class="fas fa-cog"></i> Settings</a></li>
							<li><a href="{% url 'messenger:empty-chat'%}"><i class="fab fa-rocketchat"></i> Chat</a></li>
							<li><a href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt"></i> Log Out</a></li>
							<!--<li><a href="">More</a></li>
							<li><a href="">More</a></li>
							<li><a href="">More</a></li> -->
						</ul>
						</li>
					</ul>
					</nav>
				</div>
				<!-- /top nav -->
				<div class="row row-offcanvas row-offcanvas-left">
					
					<!-- sidebar -->
					<div class="column col-sm-2 col-xs-1 sidebar-offcanvas" id="sidebar">
					  
						<ul class="nav">
							<li><a href="#" data-toggle="offcanvas" class="visible-xs text-center"><i class="glyphicon glyphicon-chevron-right"></i></a></li>
						</ul>
					   
						<ul class="nav hidden-xs" id="lg-menu">
							<li class="active"><a href=""><i class="glyphicon glyphicon-refresh"></i> Refresh</a></li>
							<li><a href="{% url 'users:account-settings' %}"><i class="fas fa-cog"></i> Account Information </a></li>
							<li><a href="{% url 'users:personal-settings'%}"><i class="fas fa-user-cog"></i> Personal Information </a></li>											
						</ul>
						<ul class="list-unstyled hidden-xs" id="sidebar-footer">
							<li>
							 <p style="font-size: 11px;">Privacy· Terms· Advertising· <br>Ad Choices <i class="fas fa-angle-double-right"></i>· Cookies· More· Facepage © 2021</p>
							</li>
						</ul>
					  
						<!-- tiny only nav-->
					  <ul class="nav visible-xs" id="xs-menu">
						    <li><a href="" class="text-center"><i class="glyphicon glyphicon-refresh"></i></a></li>
							<li><a href="{% url 'users:account-settings' %}" class="text-center"><i class="fas fa-cog"></i></a></li>
							<li><a href="{% url 'users:personal-settings'%}" class="text-center"><i class="fas fa-user-cog"></i></a></li>
						</ul>
					  
					</div>
					<!-- /sidebar -->
				  
					<!-- main right col -->
					<div class="column col-sm-10 col-xs-11" id="main">
						<div class="padding">
							<div class="full col-sm-9" >

								<div class="testbox">
									<form action="{% url 'users:account-settings' %}" method="post"> {%csrf_token%}
									  <h1>Settings</h1>
									  <br><hr>

									  <div class="item">
										<p>Account Information</p>
										<div class="name-item">
										  <input id="email" value="{{email}}" type="email" name="email" placeholder="Email" />
										  <input id="username" value="{{username}}" type="username" name="username" placeholder="Username" disabled/>
										  <input id="password1" type="password" name="password1" placeholder="Password" required/>
										  <input id="password2" type="password" name="password2" placeholder="Confirm Password" required/>					
										</div>
										<button class="buttonS" type="submit" >Save</button>								
									  </div>
									  <hr><br>
									
									
									  <br><hr>
									  <div class="item">
										
										<p>Delete Account<br><span style="color: rgb(90, 90, 90); font-size: 13px;">Think well before leaving!</span></p>
										{% if request.user.is_superuser %}
											<p>Can't delete a superuser account</p>
										{% else %}
											<p><a href="{% url 'users:delete' %}">Deleting account</a></p>
										{% endif %}
										<div class="item">
											<textarea disabled="true" rows="6" style="resize:none;" placeholder="This is permanent&#10When you delete your Facepage account, you won't be able to retrieve the content or information you've shared on Facepage. All of your messages will also be deleted."></textarea>
										</div>
									  </div>
									  <hr><br>


									</form>
								  </div>
							   <hr>
							   <h4 class="text-center">
								<p style="font-size: 11px;">Privacy· Terms· Advertising· Ad Choices <i class="fas fa-angle-double-right"></i>· Cookies· More· Facepage © 2021</p>
							   </h4>
							   <hr>
						
								
							  
							</div><!-- /col-9 -->
						</div><!-- /padding -->
					</div>
					<!-- /main -->
				  
				</div>
			</div>
		</div>


        
        <script type="text/javascript" src="{% static 'users/js/jquery.js'%}"></script>
        <script type="text/javascript" src="{% static 'users/js/bootstrap.js'%}"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				$('[data-toggle=offcanvas]').click(function() {
					$(this).toggleClass('visible-xs text-center');
					$(this).find('i').toggleClass('glyphicon-chevron-right glyphicon-chevron-left');
					$('.row-offcanvas').toggleClass('active');
					$('#lg-menu').toggleClass('hidden-xs').toggleClass('visible-xs');
					$('#xs-menu').toggleClass('visible-xs').toggleClass('hidden-xs');
					$('#btnShow').toggle();
				});
			});
			</script>
</body></html>

users/templates/users/index.html
<html>
    <head>
        {% block head %}
            <title>
            {% block title %}
                Facepage
            {% endblock title %}
            </title>
        {% endblock head %}
    </head>
    <body>
        {% block body %}
            <header>
                {% block header %}
                <h1>Welcome to facepage</h1>
                {% endblock header %}
            </header>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}
                {% if message %}<p><strong>{{message }}</strong></p>{% endif %}
                    <form action="{% url 'users:login' %}" method="POST"> {% csrf_token %}
                        <fieldset>
                            <legend>Log in</legend>
                            <label for="username">Username</label>
                            <input type="text" name="username" id="username">
                            <br>
                            <label for="password">Password</label>
                            <input type="password" name="password" id="password">
                            <br>
                            <input type="submit" value="Login">
                        </fieldset>
                    </form>
                <small>Need an account ? <a href="{% url 'users:register' %}">Register</a></small>
            {% endblock content %}
            <footer>
                {% block footer%}
                {% endblock footer %}
            </footer>
        {% endblock body %}
    </body>
</html>

users/templates/users/originalSettings.html
{% extends 'users/index.html' %}
{% block title %}
    Settings
{% endblock %}

{% block header %}
        <a href="{% url 'users:index' %}">Home</a>
{% endblock header %}
{% block content %}
    <p>
        Any changes you commits needs a password, use your old password if you don't want to change it
        <br>
        Or a new password with your new data if you want to change it
    </p>
    <div>
        <form action="{% url 'users:settings' %}" method="post"> {%csrf_token%}
            <fieldset>
                <legend>Settings</legend>
                <p>
                    <label for="username">Username</label>
                    <input type="text" value="{{username}}"name="username" id="username" disabled>
                </p>
                <p>
                    <label for="email">E-mail</label>
                    <input type="email" value="{{email}}"name="email" id="email">
                </p>
                <p>
                    <label for="password1">New password</label>
                    <input type="password" name="password1" id="password1" required>
                </p>
                <P>
                    <label for="password2">Password confirmation</label>
                    <input type="password" name="password2" id="password2" required>
                </P>
                <input type="submit" value="Save">

            </fieldset>
        </form>
    </div>
    <div class="Instructions">
        <p>Don't upload anything if you wish to not change you current profile picture</p>
    </div>
    <div class="bio">
        <fieldset>
            <legend>Bio and profile picture</legend>
            <form action="{% url 'users:change-bio' %}" method="POST" enctype="multipart/form-data"> {%csrf_token%}
                {{bio_form.as_p}}
                <input type="submit" value="Save">
            </form>
            {% if request.user.profile.profile_picture.url == '/media/profile_pics/default.jpg' %}
                <p>You don't have a profile picture to delete</p>
            {% else %}
                <a href="{% url 'users:delete-profile-picture' %}">Delete current profile picture</a>
            {% endif %}
        </fieldset>
    </div>
    
    <div class="danger-section">
        <fieldset>
            <legend>Danger section</legend>
            {% if request.user.is_superuser %}
               <p>Can't delete a superuser account</p>
            {% else %}
                <p><a href="{% url 'users:delete' %}">Deleting account</a></p>
            {% endif %}
        </fieldset>
    </div>
{% endblock content %}