facepage/urls.py
#from posts.views import getProfilePosts
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from posts.views import profile_view

urlpatterns = [
    path(r'admin/', admin.site.urls, name='admin'),
    path(r'', include('users.urls'), name='users'),
    path(r'home/', include('posts.urls'), name='home'),
    path(r'profile/<slug:link>/', profile_view, name='profile'),
    #path(r'profile/<slug:link>/get/', getProfilePosts, name='profile-posts'),
    path(r'messenger/', include('messenger.urls'), name='messenger'),
    path(r'notifications/', include('notifications.urls'), name='notifications'),
]

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),]

messenger/urls.py
from django.urls import path
from .views import *

app_name = 'messenger'
urlpatterns = [
    path(r'<str:link>/', chat_view, name='chat'),
    path(r'', chat_view, name='empty-chat'),
    path(r'<str:link>/send/', user_send_message_ajax, name='send'),
    path(r'<str:link>/get/', user_receiver_message_ajax, name='get-messages'),
]

notifications/urls.py
from django.urls import path
from . import views

app_name = 'notifications'
urlpatterns = [
    path(r'', views.notifications_view, name='index'),
    path(r'delete/<slug:id>/', views.delete_notification_ajax, name='delete-notification'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path(r'', views.home_view, name='home'),
    path(r'createpost/', views.create_post_view, name='add-post'),
    path(r'post/<int:post_id>/', views.view_post_view, name='view-post'),
    path(r'update/<int:post_id>/', views.update_post_view, name='update'),
    # path(r'like/<int:post_id>/', views.like_post_view, name='like-post'),
    # path(r'unlike/<int:post_id>/', views.unlike_post_view, name='unlike-post'),
    path(r'comment/<int:post_id>/', views.add_comment_view, name='add-comment'),
    path(r'search/', views.search_view, name='search'),
    path(r'share/<int:post_id>/', views.share_post_view, name='share-post'),
    
    #ajax
    path(r'ajax-like/<int:post_id>/', views.like_post_ajax, name='like-post-ajax'),
    path(r'ajax-unlike/<int:post_id>/', views.unlike_post_ajax, name='unlike-post-ajax'),
    path(r'ajax-comment/<int:post_id>/', views.add_comment_ajax, name='add-comment-ajax'),
    path(r'delete/<int:post_id>/', views.delete_post_ajax, name='delete'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'logout/', views.logout_view, name='logout'),
    path(r'login/', views.login_with_limit_view, name='login'),
    path(r'register/', views.register_view, name='register'),
    path(r'account-settings/', views.account_settings_view, name='account-settings'),
    path(r'delete-account/', views.delete_account_view, name='delete'),
    path(r'delete-profile-picture/', views.delete_profile_picture_view, name='delete-profile-picture'),
    path(r'delete-profile-cover/', views.delete_profile_cover_view, name='delete-profile-cover'),
    path(r'activate/<uidb64>/<token>/', views.activate_view, name='activate'),
    path(r'personal-settings/', views.personal_settings_view, name='personal-settings'),
    path(r'send-friend-request/<slug:link>/', views.send_friend_request_view, name='add-friend'),
    path(r'accept-friend-request/<slug:link>/', views.accept_friend_request_view, name='create-friend'),
    path(r'decline-friend-request/<slug:link>/', views.decline_friend_request_view, name='decline-friend'),
    path(r'unfriend/<slug:link>/', views.unfriend_view, name='unfriend'),
    path(r'cancel-friend-request/<slug:link>/', views.cancel_friend_request_view, name='cancel-friend'),
    path(r'forgot-password/', views.forgot_password_view, name='forgot-password'),   
    path(r'friends/', views.show_all_friends_view, name='friend-list'),
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model as User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

class Post(models.Model):
    post_content = models.TextField(blank=True)
    creator = models.ForeignKey(User(), on_delete=models.CASCADE)
    create_date = models.DateTimeField(default=timezone.now)
    likes = models.IntegerField(default=0)
    comments = models.IntegerField(default=0)
    image = models.ImageField(default='', blank=True, upload_to='posts_pics')
    shared_post = models.BooleanField(default=False)
    original_post = models.ForeignKey(to='self', on_delete=models.SET_NULL, null=True, blank=True)

    def clean(self, *args, **kwargs) -> None:
        if self.shared_post and self.image != '':
            raise ValidationError(_("Shared post cannot have an image"), code="image-shared-post")
        if self.post_content == '' and not self.shared_post:
            raise ValidationError(_("non-shared posts cannot have no content"), code="shared-post-no-content")
        if self.original_post != None and self.shared_post == False:
            raise ValidationError(_("non-shared posts cannot have reference to any posts"), code="non-shared-post-reference")
        if self.shared_post and self.original_post == self:
            raise ValidationError(_("shared posts cannot reference themselves"), code="self-referencing")
        return super().clean(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)
    
    def __str__(self):
        string = self.post_content[0:30]
        if len(string) == 30:
            string += "..."
        return f"{string}, Post ID: {self.id} from: {self.creator}"

class Comment(models.Model):
    comment_content = models.CharField(max_length=1000)
    creator = models.ForeignKey(User(), on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    create_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        comment = self.comment_content[0:10]
        if len(comment) > 10:
            comment += "..."
        return f"{comment}, Comment ID: {self.id} from: {self.creator} to post: {self.post}"

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    liker = models.ForeignKey(User(), on_delete=models.CASCADE)

    @staticmethod
    def is_post_liked_by_user(user: User(), post: Post):
        return Like.objects.filter(liker=user, post=post).exists()
    
    def __str__(self):
        return f"Like ID: {self.id} On Post: {self.post.id} from: {self.liker.username}"

pages/templates/pages/Base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>

<html lang="en">
    <head>
        {% block head%}
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"> 
        <meta charset="utf-8">
        <title>{%block title%}Settings{% endblock title%}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="{% static 'pages/fonts/fontawesome-free-5.15.3-web/css/all.css'%}" rel="stylesheet">
        <link href="{% static 'pages/css/bootstrap.css'%}" rel="stylesheet">
        <!--[if lt IE 9]>
          <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        {% block style_link %}
        <link href="{% static 'pages/css/facepage.css'%}" rel="stylesheet">
        {% endblock style_link %}
        {% block style %}
        {% endblock style %}
        {% endblock head %}
    </head>
    <body>
        {% block body%}
            <div class="wrapper">
                <div class="box"></div>
                    {% block navbar %}
                        <div class="navbar navbar-blue navbar-static-top" style="width: 100%;">  
                            <div class="navbar-header">
                                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                </button>
                                <a href="{% url 'users:index' %}" class="navbar-brand logo">F</a>
                            </div>
                            <nav class="collapse navbar-collapse" role="navigation">
                            <form class="navbar-form navbar-left" method="GET" action="{% url 'posts:search' %}">
                                <div class="input-group input-group-sm" style="max-width:360px;">
                                    <input class="form-control" placeholder="Search" name="search-text" id="srch-term" type="text" required>
                                    <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                    </div>
                                </div>
                            </form>
                            <ul class="nav navbar-nav">
                                {% if request.user.is_staff %}
                                <li>
                                <a href="{% url 'admin:index' %}"><i class="glyphicon glyphicon-hdd"></i> Admin panel</a>
                                </li>
                                {% endif %}
                                <li>
                                <a href="{% url 'posts:home' %}"><i class="glyphicon glyphicon-home"></i> Home</a>
                                </li>
                                <li>
                                <a href="{% url 'messenger:empty-chat' %}"><i class="fab fa-rocketchat"></i> Chat</a>
                                </li>
                                <li>
                                <a href="{% url 'notifications:index'%}"><i class="fas fa-bell"></i> Notifications</a>
                                </li>
                                <li>
                                <a href="{% url 'profile' active_user.profile.link %}"><img src="{{active_user.profile.profile_picture.url}}" class="img-circle pull-left" style="width: 40px;height: 40px; margin-top: -10px;"><span class="badge"> {{active_user.get_short_name}}</span></a>
                                </li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown"><i class="fas fa-caret-square-down fa-lg"></i></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'users:account-settings'%}"><i class="fas fa-cog"></i> Settings</a></li>
                                    <li><a href="{% url 'messenger:empty-chat'%}"><i class="fab fa-rocketchat"></i> Chat</a></li>
                                    <li><a href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt"></i> Log Out</a></li>
                                    <!--<li><a href="">More</a></li>
                                    <li><a href="">More</a></li>
                                    <li><a href="">More</a></li> -->
                                </ul>
                                </li>
                            </ul>
                            </nav>
                        </div>
                    {% endblock navbar %}
                    <div class="row row-offcanvas row-offcanvas-left">
                        {% block sidebar %}
                        {% endblock sidebar %}
                       {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{message.tags}}" style="display:flex; text-align: center; justify-content: center; font-weight: bold; color: red;">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        {% block main %}
                            
                        {% endblock main%}
                    </div>
                </div>
            </div>
        {% endblock body %}
        {% block scripts %}
            <script type="text/javascript" src="{% static 'pages/js/jquery.js'%}"></script>
            <script type="text/javascript" src="{% static 'pages/js/bootstrap.js'%}"></script>
            <script type="text/javascript">
                $(document).ready(function() {
                    $('[data-toggle=offcanvas]').click(function() {
                        $(this).toggleClass('visible-xs text-center');
                        $(this).find('i').toggleClass('glyphicon-chevron-right glyphicon-chevron-left');
                        $('.row-offcanvas').toggleClass('active');
                        $('#lg-menu').toggleClass('hidden-xs').toggleClass('visible-xs');
                        $('#xs-menu').toggleClass('visible-xs').toggleClass('hidden-xs');
                        $('#btnShow').toggle();
                    });
                });
            </script>
        {% endblock scripts %}
    </body>
</html>

pages/templates/pages/DeleteAccount.html
{% extends 'pages/BaseSettings.html' %}
{% comment %}
{% block head %}
    <title>Delete Account</title>
{% endblock %}
{% block header %}
<a href="{% url 'posts:home' %}">Home</a>
{% endblock %}
{% block content %}

    <div class="danger">
        <p>
            <strong>
                By deleting your account, you will delete all comments and posts you shared
                <br>
                think twice about your decision
                <br>
                Type your username and "I want to delete my account" in the confirmation
            </strong>
        </p>
        <form action="{% url 'users:delete' %}" method="post"> {%csrf_token%}
            {{ form.as_p }}
            <input type="submit" value="Delete">
        </form>
    </div>
{% endblock %}
{% endcomment %}
{% block main %}
<div class="column col-sm-10 col-xs-11" id="main">
    <div class="padding">
        <div class="full col-sm-9" >
            <div class="item">
                <span>
                    <strong>
                        By deleting your account, you will delete all comments and posts you shared
                        <br>
                        think twice about your decision
                        <br>
                        Type your username and "i want to delete my account" in the confirmation
                    </strong>
                </span>
                <br>
                <br>
                <form action="{% url 'users:delete' %}" method="post">
                    {%csrf_token%}
                    <label for="{{form.username.id_for_label}}">Username: </label>
                    <input id="{{form.username.id_for_label}}" name="username" type="text"> 
                    <label for="{{form.confirmation.id_for_label}}">Confirmation: </label>
                    <textarea id="{{form.confirmation.id_for_label}}" name="confirmation" rows="2" style="resize:vertical;">{{bio_form.bio.value}}</textarea>
                    <input type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

pages/templates/pages/NewHome.html
{% extends 'pages/Base.html' %}
{% load humanize %}
{% load static %}
{% block style %} {% endblock %}

{% block title%}
Facepage
{% endblock%}

{% block sidebar%}
<!-- sidebar -->
<div class="column col-sm-2 col-xs-1 sidebar-offcanvas" id="sidebar">
					  
    <ul class="nav">
        <li><a href="#" data-toggle="offcanvas" class="visible-xs text-center"><i class="glyphicon glyphicon-chevron-right"></i></a></li>
    </ul>
   
    <ul class="nav hidden-xs" id="lg-menu">
        <li class="active"><a href=""><i class="glyphicon glyphicon-refresh"></i> Refresh</a></li>
        <li><a href="{% url 'users:friend-list'%}"><i class="fas fa-user-friends"></i> Friends</a></li>
        <li><a href="#"><i class="glyphicon glyphicon-list"></i> Stories</a></li>
        <li><a href="#"><i class="fas fa-history"></i> Memories</a></li>
        <li><a href="#"><i class="fas fa-bookmark"></i> Saved</a></li>
        <li><a href="#"><i class="fas fa-users"></i> Groups</a></li>										
    </ul>
    <ul class="list-unstyled hidden-xs" id="sidebar-footer">
        <li>
         <p style="font-size: 11px;">Privacy· Terms· Advertising· <br>Ad Choices <i class="fas fa-angle-double-right"></i>· Cookies· More· Facepage © 2021</p>
        </li>
    </ul>
  
    <!-- tiny only nav-->
  <ul class="nav visible-xs" id="xs-menu">
        <li><a href="" class="text-center"><i class="glyphicon glyphicon-refresh"></i></a></li>
        <li><a href="#" class="text-center"><i class="glyphicon glyphicon-list"></i></a></li>
        <li><a href="#" class="text-center"><i class="fas fa-user-friends"></i></a></li>
        <li><a href="#" class="text-center"><i class="fas fa-history"></i></a></li>
        <li><a href="#" class="text-center"><i class="fas fa-bookmark"></i></a></li>
        <li><a href="#" class="text-center"><i class="fas fa-users"></i></a></li>
    
    </ul>
  
</div>
{% endblock sidebar%}
{% block main%}
<div class="column col-sm-10 col-xs-11" id="main">
    <div class="padding">
        <div class="full col-sm-9" >
          
            <!-- content -->                      
            <div class="row">
              
             <!-- main col left --> 
            <div class="col-sm-5">
               
                <div class="well"> 
                    <form enctype="multipart/form-data" class="form-horizontal" role="form" action="{% url 'posts:add-post' %}" method="POST"> {%csrf_token%}
                        <h4>What's New</h4>
                            <div class="form-group" style="padding:14px;">
                            <textarea name="content" class="form-control" placeholder="What's on your mind?"></textarea>
                        </div>
                        <!--this button for home post window -->
                        <button class="btn btn-primary pull-right" type="submit" value="submit">Post</button>
                        <ul class="list-inline">
                            <li>
                                <input type="file" name="image" accept="image/*">
                                <!-- <a href=""><i class="fas fa-photo-video"></i></a> -->
                            </li>
                            <li><a href=""><i class="fas fa-user-tag"></i></a></li>
                            <li><a href=""><i class="glyphicon glyphicon-map-marker"></i></a></li>
                        </ul>
                    </form>
                </div>

                    <!--  -->
                    {% for post in friends_posts %}
                    <div class="panel panel-default">
                        <div class="panel-heading" style="border-bottom: none;"	>
                            <img src="{{ post.0.creator.profile.profile_picture.url }}" class="img-circle pull-left" >
                            <h4 style="font-size: 17px; font-weight: bold;"><a href="{% url 'profile' post.0.creator.profile.link %}">{{post.0.creator.profile.name}}</a>
                                <br>
                                <p style="font-size: 13.5px; font-weight: lighter;">{{post.0.create_date|naturaltime}} <i class="fas fa-globe-americas" style="font-size: 13px;"></i></p>
                            </h4>
                        </div>
                        <p id="{{post.0.id}}-content" style="margin-left: 18px;">
                            {% if post.0.post_content|length > 222%}
                            {{post.0.post_content|slice:"0:222"}}<span class="dots">... <a id="{{post.0.id}}-show-more-button" style="font-weight: 600px;text-decoration: none;" onclick="showMoreFunction('{{post.0.id}}-content', '{{post.0.id}}-show-more-button')">See More</a></span>
                            <span style="display: none;" class="more">{{post.0.post_content|slice:"222:"}}
                            </span>
                            {% else %}
                            {{post.0.post_content}}
                            {% endif %}
                        </p>
                        <div class="panel-body">
                            {% if post.0.shared_post %}
                            {% if post.0.original_post != none %}
                            <div class="shared-post" style="border: 1px solid #dddddd; ">
                                <div class="panel-heading" ><img src="{{post.0.original_post.creator.profile.profile_picture.url}}" class="img-circle pull-left" >
                                    <!-- <button class="pull-right"><i class="fas fa-user-plus"></i></button> -->
                                    <h4 style="font-size: 17px; font-weight: bold;"><a href="{% url 'profile' post.0.original_post.creator.profile.link %}">{{post.0.original_post.creator.profile.name}}</a>
                                        <br>
                                        <p style="font-size: 13.5px; font-weight: lighter;">{{post.0.original_post.create_date|naturaltime}} <i class="fas fa-globe-americas" style="font-size: 13px;"></i></p>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <p>
                                        <a id="{{post.0.id}}-content-shared" href="{% url 'posts:view-post' post.0.original_post.id %}">
                                            {% if post.0.original_post.post_content|length > 222%}
                                            {{post.0.original_post.post_content|slice:"0:222"}}
                                            <span class="dots">... </span>
                                            <span style="display: none;" class="more">{{post.0.original_post.post_content|slice:"222:"}}</span>
                                            {% else %}
                                            {{post.0.original_post.post_content}}
                                            {% endif %}
                                        </a>
                                        {% if post.0.original_post.post_content|length > 222%}
                                            <a id="{{post.0.id}}-show-more-button-shared" style="font-weight: 600px;text-decoration: none;" onclick="showMoreFunction('{{post.0.id}}-content-shared', '{{post.0.id}}-show-more-button-shared');">See More</a></span>
                                        {% endif %}
                                    </p>
                                    {% if post.0.original_post.image != ''%}
                                    <div class="panel-thumbnail"><img src="{{post.0.original_post.image.url}}" class="img-responsive"></div>
                                    <div class="clearfix"></div>
                                    {% endif%}
                                </div>
                            </div>
                            {% else %}
                            <div class="shared-post" style="border: 1px solid #dddddd; ">
                                <p>Cannot view this post maybe it has been deleted</p>
                            </div>
                            {% endif %}
                            <br>
                            {% elif post.0.image != ''%}
                            <div class="post-img" style="border: 1px solid #dddddd;">
                                <div class="panel-body">
                                <div class="panel-thumbnail"><img src="{{post.0.image.url}}" class="img-responsive"></div>
                                <div class="clearfix"></div>
                                </div>
                            </div><!-- post-img-->
                            <br>
                            {% endif %}

                            <div class="input-group">
                                <div class="input-group-btn">
                                    {% if post.1%}
                                        <button id="{{post.0.id}}-like" onclick="likeButtonAction('{{post.0.id}}')" class="btn btn-default like" style="float: left;"><i class="fas fa-thumbs-down"></i> {{ post.0.likes }}</button>
                                    {% else %}
                                        <button id="{{post.0.id}}-like" onclick="likeButtonAction('{{post.0.id}}')" class="btn btn-default like" style="float: left;"><i class="fas fa-thumbs-up"></i> {{ post.0.likes }}</button>
                                    {% endif%}
                                    <form action="{% url 'posts:share-post' post.0.id %}" method="POST"> {%csrf_token%}
                                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-share"></i></button>
                                    </form>
                                </div>
                                <form action="{% url 'posts:add-comment' post.0.id %}" method="get"> {%csrf_token%}
                                    <input name="comment-content" class="form-control" id="CommentInput" style="margin-left: 40px;" placeholder="Add a comment.." type="text">
                                </form>
                            </div>
                            {% for comment in post.2 %}
                            <div class="comment" style="margin-top: 20px;"><!--start comment-->
                                    <img src="{{comment.creator.profile.profile_picture.url}}" class="img-circle pull-left" >
                                    <!-- <button class="pull-right"><i class="fas fa-trash"></i></button>  -->
                                    <div class="right">
                                        <h4 style="font-size: 15px; font-weight: bold; ">{{ comment.creator.profile.name }}<br>
                                            <p style="font-size: 13.5px; font-weight: 300; margin-top: 3px;">
                                                {{comment.comment_content}}
                                            </p>
                                        </h4>
                                    </div>
                                </div>
                            {% endfor%}     
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div><!--/row-->
            <hr>
            <h4 class="text-center">
                <p style="font-size: 11px;">Privacy· Terms· Advertising· Ad Choices <i class="fas fa-angle-double-right"></i>· Cookies· More· Facepage © 2021</p>
            </h4>
            <hr>
        </div><!-- /col-9 -->
    </div><!-- /padding -->
</div>
<!-- /main -->


{% endblock main%}

{% block scripts %}
{{ block.super }}
<script src="{% static 'pages/js/postShowMore.js'%}"></script>

<!-- Ajax call for liking and disliking posts -->
<script>
function likeButtonAction(buttonID)
{
    var xhr = new XMLHttpRequest()
    var button = document.getElementById(buttonID+"-like");
    var i = button.children[0]
    if(i.classList.contains("fa-thumbs-up"))
    {
        xhr.open("GET", location.protocol + "//" + location.host + "/home/ajax-like/" + buttonID +"/", true);
        xhr.onload = (e) =>
        {
            var response = JSON.parse(xhr.responseText);
            if(response.message === "good")
            {
                i.classList.replace("fa-thumbs-up", "fa-thumbs-down");
                button.innerHTML = '';
                button.appendChild(i);
                button.innerHTML += ' ' + response.likes
            }
            else
            {
                errorInLiking(button);
            }
        };
    }
    else if(i.classList.contains("fa-thumbs-down"))
    {
        xhr.open("GET", location.protocol + "//" + location.host + "/home/ajax-unlike/" + buttonID +"/", true);
        xhr.onload = (e) =>
        {
            var response = JSON.parse(xhr.responseText);
            if(response.message === "good")
            {
                i.classList.replace("fa-thumbs-down", "fa-thumbs-up");
                button.innerHTML = '';
                button.appendChild(i);
                button.innerHTML += ' ' + response.likes
            }
            else
            {
                errorInLiking(button);
            }
        };
    }

    xhr.onerror = (e) =>
    {
        errorInLiking(button)
    };
    xhr.send()
}

function errorInLiking(button)
{
    var p = document.createElement("p");
    p.innerText = "There was an error please refresh the page";
    button.parentElement.appendChild(p);
}
</script>
<script>
    const evtSource = new EventSource(window.location.protocol + "//" + window.location.host + "/events/{{active_user.profile.link}}/");
    evtSource.onmessage = (event) => {
        console.log(event.data);
      }
</script>

{% endblock scripts %}

pages/templates/pages/newAccountSettings.html
{% extends 'pages/BaseSettings.html' %}

{% block main %}
<div class="column col-sm-10 col-xs-11" id="main">
    <div class="padding">
        <div class="full col-sm-9" >

            <div class="testbox">
                <form action="{% url 'users:account-settings' %}" method="post"> {%csrf_token%}
                  <h1>Account Settings</h1>
                  <br><hr>

                  <div class="item">
                    <p>Account Information</p>
                    <div class="name-item">
                      <input id="email" value="{{email}}" type="email" name="email" placeholder="Email" disabled />
                      <input id="username" value="{{username}}" type="username" name="username" placeholder="Username" disabled/>
                      <input id="password1" type="password" name="password1" placeholder="Password" required/>
                      <input id="password2" type="password" name="password2" placeholder="Confirm Password" required/>					
                    </div>
                    <button class="buttonS" type="submit" >Save</button>								
                  </div>
                  <hr><br>
                  <br><hr>
                  <div class="item">
                    
                    <p>Delete Account<br><span style="color: rgb(90, 90, 90); font-size: 13px;">Think well before leaving!</span></p>
                    {% if request.user.is_superuser %}
                        <p>Can't delete a superuser account</p>
                    {% else %}
                        <p><a href="{% url 'users:delete' %}">Deleting account</a></p>
                    {% endif %}
                    <div class="item">
                        <textarea disabled="true" rows="6" style="resize:none;" placeholder="This is permanent&#10When you delete your Facepage account, you won't be able to retrieve the content or information you've shared on Facepage. All of your messages will also be deleted."></textarea>
                    </div>
                  </div>
                  <hr><br>


                </form>
              </div>
           <hr>
           <h4 class="text-center">
            <p style="font-size: 11px;">Privacy· Terms· Advertising· Ad Choices <i class="fas fa-angle-double-right"></i>· Cookies· More· Facepage © 2021</p>
           </h4>
           <hr>
    
            
          
        </div><!-- /col-9 -->
    </div><!-- /padding -->
</div>
{% endblock main %}